apiVersion: v1
kind: Service
metadata:
  name: ai-code-service
spec:
  type: NodePort
  selector:
    app: ai-code-assistant
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
