deployment:
  replicas: 1

image:
  repository: eshbah/ai-powered-code-generator-application
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 80
  nodePort: 30081

containerPort: 5000

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
